### ISSUE TITLE
Move nordsoftware/lumen-newrelic to "suggests"

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/lumen-graphql#14]
The library is not needed for normal operation, so we should make it optional.

**Comment by Jalle19** [comment]
@crisu83 https://travis-ci.org/digiaonline/lumen-graphql/jobs/337311464 can you fix the build? Not sure what the best way to test suggested dependencies is, might be worth looking at how other projects do it.

**Comment by cniska** [comment]
Remove the test.

**Comment by cniska** [comment]
Or add it to requiredev.

**Comment by cniska** [comment]
Maybe latter.

**Comment by Jalle19** [comment]
`require-dev` is a good idea, try that

**Comment by Jalle19** [comment]
Replaced by https://github.com/digiaonline/lumen-graphql/issues/20
