### ISSUE TITLE
Add suggested dependencies to require-dev

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/lumen-graphql#20]
Without this the test cases for them won't pass

**Comment by q-hung** [comment]
It is funny that when I run `composer sugggests` it returns many things excepts the package we added in `suggest`

```
composer suggests
ext-libsodium
ext-uopz
guzzlehttp/guzzle
league/flysystem
league/flysystem-aws-s3-v3
league/flysystem-rackspace
mtdowling/cron-expression
phpunit/php-invoker
symfony/browser-kit
symfony/config
symfony/dependency-injection
symfony/lock
symfony/var-dumper
```

This is also a package to install suggest package, it's not likely that we want to use it https://github.com/nfreear/composer-suggest

**Comment by Jalle19** [comment]
You would probably have to run composer update since we don't have the lock file committed. Either way I think require-dev is the right way to go in this case.
