### ISSUE TITLE
README badges

### ISSUE THREAD

**Issue by cniska** [digiaonline/lumen-graphql#3]
* [x] Build
* [x] Coverage Status
* [ ] Code Climate
* [x] Scrutinizer Code Quality
* [ ] StyleCI
* [x] Latest Stable Version
* [x] Total Downloads
* [x] License
* [x] Gitter

**Comment by hugovk** [comment]
Some were added in https://github.com/digiaonline/lumen-graphql/pull/7. Others are awaiting CI stuff.

**Comment by Jalle19** [comment]
Scrutinizer can be added even without tests etc.

**Comment by Jalle19** [comment]
I think we can manage without Code Climate and StyleCI for now
