### ISSUE TITLE
Make PHP 7.1 a minimum requirement

### ISSUE THREAD

**Issue by Jalle19** [digiaonline/lumen-graphql#4]
Makes no sense to support older versions anymore in my opinion

**Comment by cniska** [comment]
@Jalle19 I'd rather not, because that will seriously limit the amount of people that can benefit from this module.

**Comment by Jalle19** [comment]
The README says Laravel 5.5 is required and that itself requires PHP 7.0+: https://laravel-news.com/laravel-5-5-php-7-0

**Comment by cniska** [comment]
@Jalle19 I see, I think we can change that to Laravel / Lumen 5.3 in that case.

**Comment by Jalle19** [comment]
Should we reconsider this? 7.1 becomes more relevant every day.

**Comment by hugovk** [comment]
Stats from packagist.org from November 2017:

![image](https://user-images.githubusercontent.com/1324225/34770560-2411f0cc-f60a-11e7-98e9-23793b31e989.png)

![image](https://user-images.githubusercontent.com/1324225/34770746-adb7aa6a-f60a-11e7-85bf-f412a1b6637a.png)

https://seld.be/notes/php-versions-stats-2017-2-edition

PHP 5.6 is dropping quite significantly.

---

And of course, PHP 5.6 itself (like PHP 7.0) is not actively supported, only receiving critical security issues.

https://secure.php.net/supported-versions.php

**Comment by Jalle19** [comment]
I would go straight for 7.1, after all we're making these packages because we use them ourselves, not to please everyone on the planet.

**Comment by Jalle19** [comment]
This was recently done

**Comment by Jalle19** [comment]
Actually the README still needs to be updated

**Comment by Jalle19** [comment]
Fixed in https://github.com/digiaonline/lumen-graphql/commit/fc933b65659513ea0b3763cd23e9c7e0ef2e4886
